/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppGestionRouteImport } from './routes/_app.gestion'
import { Route as AppVoaeIndexRouteImport } from './routes/_app.voae.index'
import { Route as AppTutorIndexRouteImport } from './routes/_app.tutor.index'
import { Route as AppStudentIndexRouteImport } from './routes/_app.student.index'
import { Route as AppGestionIndexRouteImport } from './routes/_app.gestion.index'
import { Route as AppEmpleadoIndexRouteImport } from './routes/_app.empleado.index'
import { Route as AppVoaeRecreacionRouteImport } from './routes/_app.voae.recreacion'
import { Route as AppVoaeRecordsRouteImport } from './routes/_app.voae.records'
import { Route as AppVoaeMuroRouteImport } from './routes/_app.voae.muro'
import { Route as AppVoaeModeradoresRouteImport } from './routes/_app.voae.moderadores'
import { Route as AppVoaeFeedRouteImport } from './routes/_app.voae.feed'
import { Route as AppVoaeCentrosRouteImport } from './routes/_app.voae.centros'
import { Route as AppTutorLiveRouteImport } from './routes/_app.tutor.live'
import { Route as AppTutorHistoryRouteImport } from './routes/_app.tutor.history'
import { Route as AppTutorFeedRouteImport } from './routes/_app.tutor.feed'
import { Route as AppTutorEventosRouteImport } from './routes/_app.tutor.eventos'
import { Route as AppTutorCreateRouteImport } from './routes/_app.tutor.create'
import { Route as AppStudentSurveyRouteImport } from './routes/_app.student.survey'
import { Route as AppStudentSolicitarRouteImport } from './routes/_app.student.solicitar'
import { Route as AppStudentPerfilRouteImport } from './routes/_app.student.perfil'
import { Route as AppStudentMuroRouteImport } from './routes/_app.student.muro'
import { Route as AppStudentMisEventosRouteImport } from './routes/_app.student.mis-eventos'
import { Route as AppStudentHistoryRouteImport } from './routes/_app.student.history'
import { Route as AppStudentFeedRouteImport } from './routes/_app.student.feed'
import { Route as AppStudentEventsRouteImport } from './routes/_app.student.events'
import { Route as AppEmpleadoPerfilRouteImport } from './routes/_app.empleado.perfil'
import { Route as AppEmpleadoMuroRouteImport } from './routes/_app.empleado.muro'
import { Route as AppEmpleadoLiveRouteImport } from './routes/_app.empleado.live'
import { Route as AppEmpleadoHistoryRouteImport } from './routes/_app.empleado.history'
import { Route as AppEmpleadoFeedRouteImport } from './routes/_app.empleado.feed'
import { Route as AppEmpleadoEventosRouteImport } from './routes/_app.empleado.eventos'
import { Route as AppEmpleadoCreateRouteImport } from './routes/_app.empleado.create'
import { Route as AppStudentEventsIndexRouteImport } from './routes/_app.student.events.index'
import { Route as AppVoaeEventsIdRouteImport } from './routes/_app.voae.events.$id'
import { Route as AppTutorEventsIdRouteImport } from './routes/_app.tutor.events.$id'
import { Route as AppStudentEventsIdRouteImport } from './routes/_app.student.events.$id'
import { Route as AppEmpleadoModeradorEventosRouteImport } from './routes/_app.empleado.moderador.eventos'
import { Route as AppEmpleadoEventsIdRouteImport } from './routes/_app.empleado.events.$id'
import { Route as AppVoaeEventsIdValidacionRouteImport } from './routes/_app.voae.events.$id.validacion'

const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGestionRoute = AppGestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => AppRoute,
} as any)
const AppVoaeIndexRoute = AppVoaeIndexRouteImport.update({
  id: '/voae/',
  path: '/voae/',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorIndexRoute = AppTutorIndexRouteImport.update({
  id: '/tutor/',
  path: '/tutor/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentIndexRoute = AppStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => AppRoute,
} as any)
const AppGestionIndexRoute = AppGestionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGestionRoute,
} as any)
const AppEmpleadoIndexRoute = AppEmpleadoIndexRouteImport.update({
  id: '/empleado/',
  path: '/empleado/',
  getParentRoute: () => AppRoute,
} as any)
const AppVoaeRecreacionRoute = AppVoaeRecreacionRouteImport.update({
  id: '/voae/recreacion',
  path: '/voae/recreacion',
  getParentRoute: () => AppRoute,
} as any)
const AppVoaeRecordsRoute = AppVoaeRecordsRouteImport.update({
  id: '/voae/records',
  path: '/voae/records',
  getParentRoute: () => AppRoute,
} as any)
const AppVoaeMuroRoute = AppVoaeMuroRouteImport.update({
  id: '/voae/muro',
  path: '/voae/muro',
  getParentRoute: () => AppRoute,
} as any)
const AppVoaeModeradoresRoute = AppVoaeModeradoresRouteImport.update({
  id: '/voae/moderadores',
  path: '/voae/moderadores',
  getParentRoute: () => AppRoute,
} as any)
const AppVoaeFeedRoute = AppVoaeFeedRouteImport.update({
  id: '/voae/feed',
  path: '/voae/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppVoaeCentrosRoute = AppVoaeCentrosRouteImport.update({
  id: '/voae/centros',
  path: '/voae/centros',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorLiveRoute = AppTutorLiveRouteImport.update({
  id: '/tutor/live',
  path: '/tutor/live',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorHistoryRoute = AppTutorHistoryRouteImport.update({
  id: '/tutor/history',
  path: '/tutor/history',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorFeedRoute = AppTutorFeedRouteImport.update({
  id: '/tutor/feed',
  path: '/tutor/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorEventosRoute = AppTutorEventosRouteImport.update({
  id: '/tutor/eventos',
  path: '/tutor/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorCreateRoute = AppTutorCreateRouteImport.update({
  id: '/tutor/create',
  path: '/tutor/create',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentSurveyRoute = AppStudentSurveyRouteImport.update({
  id: '/student/survey',
  path: '/student/survey',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentSolicitarRoute = AppStudentSolicitarRouteImport.update({
  id: '/student/solicitar',
  path: '/student/solicitar',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentPerfilRoute = AppStudentPerfilRouteImport.update({
  id: '/student/perfil',
  path: '/student/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentMuroRoute = AppStudentMuroRouteImport.update({
  id: '/student/muro',
  path: '/student/muro',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentMisEventosRoute = AppStudentMisEventosRouteImport.update({
  id: '/student/mis-eventos',
  path: '/student/mis-eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentHistoryRoute = AppStudentHistoryRouteImport.update({
  id: '/student/history',
  path: '/student/history',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentFeedRoute = AppStudentFeedRouteImport.update({
  id: '/student/feed',
  path: '/student/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentEventsRoute = AppStudentEventsRouteImport.update({
  id: '/student/events',
  path: '/student/events',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadoPerfilRoute = AppEmpleadoPerfilRouteImport.update({
  id: '/empleado/perfil',
  path: '/empleado/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadoMuroRoute = AppEmpleadoMuroRouteImport.update({
  id: '/empleado/muro',
  path: '/empleado/muro',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadoLiveRoute = AppEmpleadoLiveRouteImport.update({
  id: '/empleado/live',
  path: '/empleado/live',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadoHistoryRoute = AppEmpleadoHistoryRouteImport.update({
  id: '/empleado/history',
  path: '/empleado/history',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadoFeedRoute = AppEmpleadoFeedRouteImport.update({
  id: '/empleado/feed',
  path: '/empleado/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadoEventosRoute = AppEmpleadoEventosRouteImport.update({
  id: '/empleado/eventos',
  path: '/empleado/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadoCreateRoute = AppEmpleadoCreateRouteImport.update({
  id: '/empleado/create',
  path: '/empleado/create',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentEventsIndexRoute = AppStudentEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStudentEventsRoute,
} as any)
const AppVoaeEventsIdRoute = AppVoaeEventsIdRouteImport.update({
  id: '/voae/events/$id',
  path: '/voae/events/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorEventsIdRoute = AppTutorEventsIdRouteImport.update({
  id: '/tutor/events/$id',
  path: '/tutor/events/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentEventsIdRoute = AppStudentEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppStudentEventsRoute,
} as any)
const AppEmpleadoModeradorEventosRoute =
  AppEmpleadoModeradorEventosRouteImport.update({
    id: '/empleado/moderador/eventos',
    path: '/empleado/moderador/eventos',
    getParentRoute: () => AppRoute,
  } as any)
const AppEmpleadoEventsIdRoute = AppEmpleadoEventsIdRouteImport.update({
  id: '/empleado/events/$id',
  path: '/empleado/events/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVoaeEventsIdValidacionRoute =
  AppVoaeEventsIdValidacionRouteImport.update({
    id: '/validacion',
    path: '/validacion',
    getParentRoute: () => AppVoaeEventsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verificar': typeof VerificarRoute
  '/gestion': typeof AppGestionRouteWithChildren
  '/empleado/create': typeof AppEmpleadoCreateRoute
  '/empleado/eventos': typeof AppEmpleadoEventosRoute
  '/empleado/feed': typeof AppEmpleadoFeedRoute
  '/empleado/history': typeof AppEmpleadoHistoryRoute
  '/empleado/live': typeof AppEmpleadoLiveRoute
  '/empleado/muro': typeof AppEmpleadoMuroRoute
  '/empleado/perfil': typeof AppEmpleadoPerfilRoute
  '/student/events': typeof AppStudentEventsRouteWithChildren
  '/student/feed': typeof AppStudentFeedRoute
  '/student/history': typeof AppStudentHistoryRoute
  '/student/mis-eventos': typeof AppStudentMisEventosRoute
  '/student/muro': typeof AppStudentMuroRoute
  '/student/perfil': typeof AppStudentPerfilRoute
  '/student/solicitar': typeof AppStudentSolicitarRoute
  '/student/survey': typeof AppStudentSurveyRoute
  '/tutor/create': typeof AppTutorCreateRoute
  '/tutor/eventos': typeof AppTutorEventosRoute
  '/tutor/feed': typeof AppTutorFeedRoute
  '/tutor/history': typeof AppTutorHistoryRoute
  '/tutor/live': typeof AppTutorLiveRoute
  '/voae/centros': typeof AppVoaeCentrosRoute
  '/voae/feed': typeof AppVoaeFeedRoute
  '/voae/moderadores': typeof AppVoaeModeradoresRoute
  '/voae/muro': typeof AppVoaeMuroRoute
  '/voae/records': typeof AppVoaeRecordsRoute
  '/voae/recreacion': typeof AppVoaeRecreacionRoute
  '/empleado/': typeof AppEmpleadoIndexRoute
  '/gestion/': typeof AppGestionIndexRoute
  '/student/': typeof AppStudentIndexRoute
  '/tutor/': typeof AppTutorIndexRoute
  '/voae/': typeof AppVoaeIndexRoute
  '/empleado/events/$id': typeof AppEmpleadoEventsIdRoute
  '/empleado/moderador/eventos': typeof AppEmpleadoModeradorEventosRoute
  '/student/events/$id': typeof AppStudentEventsIdRoute
  '/tutor/events/$id': typeof AppTutorEventsIdRoute
  '/voae/events/$id': typeof AppVoaeEventsIdRouteWithChildren
  '/student/events/': typeof AppStudentEventsIndexRoute
  '/voae/events/$id/validacion': typeof AppVoaeEventsIdValidacionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verificar': typeof VerificarRoute
  '/empleado/create': typeof AppEmpleadoCreateRoute
  '/empleado/eventos': typeof AppEmpleadoEventosRoute
  '/empleado/feed': typeof AppEmpleadoFeedRoute
  '/empleado/history': typeof AppEmpleadoHistoryRoute
  '/empleado/live': typeof AppEmpleadoLiveRoute
  '/empleado/muro': typeof AppEmpleadoMuroRoute
  '/empleado/perfil': typeof AppEmpleadoPerfilRoute
  '/student/feed': typeof AppStudentFeedRoute
  '/student/history': typeof AppStudentHistoryRoute
  '/student/mis-eventos': typeof AppStudentMisEventosRoute
  '/student/muro': typeof AppStudentMuroRoute
  '/student/perfil': typeof AppStudentPerfilRoute
  '/student/solicitar': typeof AppStudentSolicitarRoute
  '/student/survey': typeof AppStudentSurveyRoute
  '/tutor/create': typeof AppTutorCreateRoute
  '/tutor/eventos': typeof AppTutorEventosRoute
  '/tutor/feed': typeof AppTutorFeedRoute
  '/tutor/history': typeof AppTutorHistoryRoute
  '/tutor/live': typeof AppTutorLiveRoute
  '/voae/centros': typeof AppVoaeCentrosRoute
  '/voae/feed': typeof AppVoaeFeedRoute
  '/voae/moderadores': typeof AppVoaeModeradoresRoute
  '/voae/muro': typeof AppVoaeMuroRoute
  '/voae/records': typeof AppVoaeRecordsRoute
  '/voae/recreacion': typeof AppVoaeRecreacionRoute
  '/empleado': typeof AppEmpleadoIndexRoute
  '/gestion': typeof AppGestionIndexRoute
  '/student': typeof AppStudentIndexRoute
  '/tutor': typeof AppTutorIndexRoute
  '/voae': typeof AppVoaeIndexRoute
  '/empleado/events/$id': typeof AppEmpleadoEventsIdRoute
  '/empleado/moderador/eventos': typeof AppEmpleadoModeradorEventosRoute
  '/student/events/$id': typeof AppStudentEventsIdRoute
  '/tutor/events/$id': typeof AppTutorEventsIdRoute
  '/voae/events/$id': typeof AppVoaeEventsIdRouteWithChildren
  '/student/events': typeof AppStudentEventsIndexRoute
  '/voae/events/$id/validacion': typeof AppVoaeEventsIdValidacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/verificar': typeof VerificarRoute
  '/_app/gestion': typeof AppGestionRouteWithChildren
  '/_app/empleado/create': typeof AppEmpleadoCreateRoute
  '/_app/empleado/eventos': typeof AppEmpleadoEventosRoute
  '/_app/empleado/feed': typeof AppEmpleadoFeedRoute
  '/_app/empleado/history': typeof AppEmpleadoHistoryRoute
  '/_app/empleado/live': typeof AppEmpleadoLiveRoute
  '/_app/empleado/muro': typeof AppEmpleadoMuroRoute
  '/_app/empleado/perfil': typeof AppEmpleadoPerfilRoute
  '/_app/student/events': typeof AppStudentEventsRouteWithChildren
  '/_app/student/feed': typeof AppStudentFeedRoute
  '/_app/student/history': typeof AppStudentHistoryRoute
  '/_app/student/mis-eventos': typeof AppStudentMisEventosRoute
  '/_app/student/muro': typeof AppStudentMuroRoute
  '/_app/student/perfil': typeof AppStudentPerfilRoute
  '/_app/student/solicitar': typeof AppStudentSolicitarRoute
  '/_app/student/survey': typeof AppStudentSurveyRoute
  '/_app/tutor/create': typeof AppTutorCreateRoute
  '/_app/tutor/eventos': typeof AppTutorEventosRoute
  '/_app/tutor/feed': typeof AppTutorFeedRoute
  '/_app/tutor/history': typeof AppTutorHistoryRoute
  '/_app/tutor/live': typeof AppTutorLiveRoute
  '/_app/voae/centros': typeof AppVoaeCentrosRoute
  '/_app/voae/feed': typeof AppVoaeFeedRoute
  '/_app/voae/moderadores': typeof AppVoaeModeradoresRoute
  '/_app/voae/muro': typeof AppVoaeMuroRoute
  '/_app/voae/records': typeof AppVoaeRecordsRoute
  '/_app/voae/recreacion': typeof AppVoaeRecreacionRoute
  '/_app/empleado/': typeof AppEmpleadoIndexRoute
  '/_app/gestion/': typeof AppGestionIndexRoute
  '/_app/student/': typeof AppStudentIndexRoute
  '/_app/tutor/': typeof AppTutorIndexRoute
  '/_app/voae/': typeof AppVoaeIndexRoute
  '/_app/empleado/events/$id': typeof AppEmpleadoEventsIdRoute
  '/_app/empleado/moderador/eventos': typeof AppEmpleadoModeradorEventosRoute
  '/_app/student/events/$id': typeof AppStudentEventsIdRoute
  '/_app/tutor/events/$id': typeof AppTutorEventsIdRoute
  '/_app/voae/events/$id': typeof AppVoaeEventsIdRouteWithChildren
  '/_app/student/events/': typeof AppStudentEventsIndexRoute
  '/_app/voae/events/$id/validacion': typeof AppVoaeEventsIdValidacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/verificar'
    | '/gestion'
    | '/empleado/create'
    | '/empleado/eventos'
    | '/empleado/feed'
    | '/empleado/history'
    | '/empleado/live'
    | '/empleado/muro'
    | '/empleado/perfil'
    | '/student/events'
    | '/student/feed'
    | '/student/history'
    | '/student/mis-eventos'
    | '/student/muro'
    | '/student/perfil'
    | '/student/solicitar'
    | '/student/survey'
    | '/tutor/create'
    | '/tutor/eventos'
    | '/tutor/feed'
    | '/tutor/history'
    | '/tutor/live'
    | '/voae/centros'
    | '/voae/feed'
    | '/voae/moderadores'
    | '/voae/muro'
    | '/voae/records'
    | '/voae/recreacion'
    | '/empleado/'
    | '/gestion/'
    | '/student/'
    | '/tutor/'
    | '/voae/'
    | '/empleado/events/$id'
    | '/empleado/moderador/eventos'
    | '/student/events/$id'
    | '/tutor/events/$id'
    | '/voae/events/$id'
    | '/student/events/'
    | '/voae/events/$id/validacion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verificar'
    | '/empleado/create'
    | '/empleado/eventos'
    | '/empleado/feed'
    | '/empleado/history'
    | '/empleado/live'
    | '/empleado/muro'
    | '/empleado/perfil'
    | '/student/feed'
    | '/student/history'
    | '/student/mis-eventos'
    | '/student/muro'
    | '/student/perfil'
    | '/student/solicitar'
    | '/student/survey'
    | '/tutor/create'
    | '/tutor/eventos'
    | '/tutor/feed'
    | '/tutor/history'
    | '/tutor/live'
    | '/voae/centros'
    | '/voae/feed'
    | '/voae/moderadores'
    | '/voae/muro'
    | '/voae/records'
    | '/voae/recreacion'
    | '/empleado'
    | '/gestion'
    | '/student'
    | '/tutor'
    | '/voae'
    | '/empleado/events/$id'
    | '/empleado/moderador/eventos'
    | '/student/events/$id'
    | '/tutor/events/$id'
    | '/voae/events/$id'
    | '/student/events'
    | '/voae/events/$id/validacion'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/verificar'
    | '/_app/gestion'
    | '/_app/empleado/create'
    | '/_app/empleado/eventos'
    | '/_app/empleado/feed'
    | '/_app/empleado/history'
    | '/_app/empleado/live'
    | '/_app/empleado/muro'
    | '/_app/empleado/perfil'
    | '/_app/student/events'
    | '/_app/student/feed'
    | '/_app/student/history'
    | '/_app/student/mis-eventos'
    | '/_app/student/muro'
    | '/_app/student/perfil'
    | '/_app/student/solicitar'
    | '/_app/student/survey'
    | '/_app/tutor/create'
    | '/_app/tutor/eventos'
    | '/_app/tutor/feed'
    | '/_app/tutor/history'
    | '/_app/tutor/live'
    | '/_app/voae/centros'
    | '/_app/voae/feed'
    | '/_app/voae/moderadores'
    | '/_app/voae/muro'
    | '/_app/voae/records'
    | '/_app/voae/recreacion'
    | '/_app/empleado/'
    | '/_app/gestion/'
    | '/_app/student/'
    | '/_app/tutor/'
    | '/_app/voae/'
    | '/_app/empleado/events/$id'
    | '/_app/empleado/moderador/eventos'
    | '/_app/student/events/$id'
    | '/_app/tutor/events/$id'
    | '/_app/voae/events/$id'
    | '/_app/student/events/'
    | '/_app/voae/events/$id/validacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  VerificarRoute: typeof VerificarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/gestion': {
      id: '/_app/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof AppGestionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voae/': {
      id: '/_app/voae/'
      path: '/voae'
      fullPath: '/voae/'
      preLoaderRoute: typeof AppVoaeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor/': {
      id: '/_app/tutor/'
      path: '/tutor'
      fullPath: '/tutor/'
      preLoaderRoute: typeof AppTutorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/': {
      id: '/_app/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AppStudentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestion/': {
      id: '/_app/gestion/'
      path: '/'
      fullPath: '/gestion/'
      preLoaderRoute: typeof AppGestionIndexRouteImport
      parentRoute: typeof AppGestionRoute
    }
    '/_app/empleado/': {
      id: '/_app/empleado/'
      path: '/empleado'
      fullPath: '/empleado/'
      preLoaderRoute: typeof AppEmpleadoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voae/recreacion': {
      id: '/_app/voae/recreacion'
      path: '/voae/recreacion'
      fullPath: '/voae/recreacion'
      preLoaderRoute: typeof AppVoaeRecreacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voae/records': {
      id: '/_app/voae/records'
      path: '/voae/records'
      fullPath: '/voae/records'
      preLoaderRoute: typeof AppVoaeRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voae/muro': {
      id: '/_app/voae/muro'
      path: '/voae/muro'
      fullPath: '/voae/muro'
      preLoaderRoute: typeof AppVoaeMuroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voae/moderadores': {
      id: '/_app/voae/moderadores'
      path: '/voae/moderadores'
      fullPath: '/voae/moderadores'
      preLoaderRoute: typeof AppVoaeModeradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voae/feed': {
      id: '/_app/voae/feed'
      path: '/voae/feed'
      fullPath: '/voae/feed'
      preLoaderRoute: typeof AppVoaeFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voae/centros': {
      id: '/_app/voae/centros'
      path: '/voae/centros'
      fullPath: '/voae/centros'
      preLoaderRoute: typeof AppVoaeCentrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor/live': {
      id: '/_app/tutor/live'
      path: '/tutor/live'
      fullPath: '/tutor/live'
      preLoaderRoute: typeof AppTutorLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor/history': {
      id: '/_app/tutor/history'
      path: '/tutor/history'
      fullPath: '/tutor/history'
      preLoaderRoute: typeof AppTutorHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor/feed': {
      id: '/_app/tutor/feed'
      path: '/tutor/feed'
      fullPath: '/tutor/feed'
      preLoaderRoute: typeof AppTutorFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor/eventos': {
      id: '/_app/tutor/eventos'
      path: '/tutor/eventos'
      fullPath: '/tutor/eventos'
      preLoaderRoute: typeof AppTutorEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor/create': {
      id: '/_app/tutor/create'
      path: '/tutor/create'
      fullPath: '/tutor/create'
      preLoaderRoute: typeof AppTutorCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/survey': {
      id: '/_app/student/survey'
      path: '/student/survey'
      fullPath: '/student/survey'
      preLoaderRoute: typeof AppStudentSurveyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/solicitar': {
      id: '/_app/student/solicitar'
      path: '/student/solicitar'
      fullPath: '/student/solicitar'
      preLoaderRoute: typeof AppStudentSolicitarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/perfil': {
      id: '/_app/student/perfil'
      path: '/student/perfil'
      fullPath: '/student/perfil'
      preLoaderRoute: typeof AppStudentPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/muro': {
      id: '/_app/student/muro'
      path: '/student/muro'
      fullPath: '/student/muro'
      preLoaderRoute: typeof AppStudentMuroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/mis-eventos': {
      id: '/_app/student/mis-eventos'
      path: '/student/mis-eventos'
      fullPath: '/student/mis-eventos'
      preLoaderRoute: typeof AppStudentMisEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/history': {
      id: '/_app/student/history'
      path: '/student/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof AppStudentHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/feed': {
      id: '/_app/student/feed'
      path: '/student/feed'
      fullPath: '/student/feed'
      preLoaderRoute: typeof AppStudentFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/events': {
      id: '/_app/student/events'
      path: '/student/events'
      fullPath: '/student/events'
      preLoaderRoute: typeof AppStudentEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleado/perfil': {
      id: '/_app/empleado/perfil'
      path: '/empleado/perfil'
      fullPath: '/empleado/perfil'
      preLoaderRoute: typeof AppEmpleadoPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleado/muro': {
      id: '/_app/empleado/muro'
      path: '/empleado/muro'
      fullPath: '/empleado/muro'
      preLoaderRoute: typeof AppEmpleadoMuroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleado/live': {
      id: '/_app/empleado/live'
      path: '/empleado/live'
      fullPath: '/empleado/live'
      preLoaderRoute: typeof AppEmpleadoLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleado/history': {
      id: '/_app/empleado/history'
      path: '/empleado/history'
      fullPath: '/empleado/history'
      preLoaderRoute: typeof AppEmpleadoHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleado/feed': {
      id: '/_app/empleado/feed'
      path: '/empleado/feed'
      fullPath: '/empleado/feed'
      preLoaderRoute: typeof AppEmpleadoFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleado/eventos': {
      id: '/_app/empleado/eventos'
      path: '/empleado/eventos'
      fullPath: '/empleado/eventos'
      preLoaderRoute: typeof AppEmpleadoEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleado/create': {
      id: '/_app/empleado/create'
      path: '/empleado/create'
      fullPath: '/empleado/create'
      preLoaderRoute: typeof AppEmpleadoCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/events/': {
      id: '/_app/student/events/'
      path: '/'
      fullPath: '/student/events/'
      preLoaderRoute: typeof AppStudentEventsIndexRouteImport
      parentRoute: typeof AppStudentEventsRoute
    }
    '/_app/voae/events/$id': {
      id: '/_app/voae/events/$id'
      path: '/voae/events/$id'
      fullPath: '/voae/events/$id'
      preLoaderRoute: typeof AppVoaeEventsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor/events/$id': {
      id: '/_app/tutor/events/$id'
      path: '/tutor/events/$id'
      fullPath: '/tutor/events/$id'
      preLoaderRoute: typeof AppTutorEventsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/events/$id': {
      id: '/_app/student/events/$id'
      path: '/$id'
      fullPath: '/student/events/$id'
      preLoaderRoute: typeof AppStudentEventsIdRouteImport
      parentRoute: typeof AppStudentEventsRoute
    }
    '/_app/empleado/moderador/eventos': {
      id: '/_app/empleado/moderador/eventos'
      path: '/empleado/moderador/eventos'
      fullPath: '/empleado/moderador/eventos'
      preLoaderRoute: typeof AppEmpleadoModeradorEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleado/events/$id': {
      id: '/_app/empleado/events/$id'
      path: '/empleado/events/$id'
      fullPath: '/empleado/events/$id'
      preLoaderRoute: typeof AppEmpleadoEventsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voae/events/$id/validacion': {
      id: '/_app/voae/events/$id/validacion'
      path: '/validacion'
      fullPath: '/voae/events/$id/validacion'
      preLoaderRoute: typeof AppVoaeEventsIdValidacionRouteImport
      parentRoute: typeof AppVoaeEventsIdRoute
    }
  }
}

interface AppGestionRouteChildren {
  AppGestionIndexRoute: typeof AppGestionIndexRoute
}

const AppGestionRouteChildren: AppGestionRouteChildren = {
  AppGestionIndexRoute: AppGestionIndexRoute,
}

const AppGestionRouteWithChildren = AppGestionRoute._addFileChildren(
  AppGestionRouteChildren,
)

interface AppStudentEventsRouteChildren {
  AppStudentEventsIdRoute: typeof AppStudentEventsIdRoute
  AppStudentEventsIndexRoute: typeof AppStudentEventsIndexRoute
}

const AppStudentEventsRouteChildren: AppStudentEventsRouteChildren = {
  AppStudentEventsIdRoute: AppStudentEventsIdRoute,
  AppStudentEventsIndexRoute: AppStudentEventsIndexRoute,
}

const AppStudentEventsRouteWithChildren =
  AppStudentEventsRoute._addFileChildren(AppStudentEventsRouteChildren)

interface AppVoaeEventsIdRouteChildren {
  AppVoaeEventsIdValidacionRoute: typeof AppVoaeEventsIdValidacionRoute
}

const AppVoaeEventsIdRouteChildren: AppVoaeEventsIdRouteChildren = {
  AppVoaeEventsIdValidacionRoute: AppVoaeEventsIdValidacionRoute,
}

const AppVoaeEventsIdRouteWithChildren = AppVoaeEventsIdRoute._addFileChildren(
  AppVoaeEventsIdRouteChildren,
)

interface AppRouteChildren {
  AppGestionRoute: typeof AppGestionRouteWithChildren
  AppEmpleadoCreateRoute: typeof AppEmpleadoCreateRoute
  AppEmpleadoEventosRoute: typeof AppEmpleadoEventosRoute
  AppEmpleadoFeedRoute: typeof AppEmpleadoFeedRoute
  AppEmpleadoHistoryRoute: typeof AppEmpleadoHistoryRoute
  AppEmpleadoLiveRoute: typeof AppEmpleadoLiveRoute
  AppEmpleadoMuroRoute: typeof AppEmpleadoMuroRoute
  AppEmpleadoPerfilRoute: typeof AppEmpleadoPerfilRoute
  AppStudentEventsRoute: typeof AppStudentEventsRouteWithChildren
  AppStudentFeedRoute: typeof AppStudentFeedRoute
  AppStudentHistoryRoute: typeof AppStudentHistoryRoute
  AppStudentMisEventosRoute: typeof AppStudentMisEventosRoute
  AppStudentMuroRoute: typeof AppStudentMuroRoute
  AppStudentPerfilRoute: typeof AppStudentPerfilRoute
  AppStudentSolicitarRoute: typeof AppStudentSolicitarRoute
  AppStudentSurveyRoute: typeof AppStudentSurveyRoute
  AppTutorCreateRoute: typeof AppTutorCreateRoute
  AppTutorEventosRoute: typeof AppTutorEventosRoute
  AppTutorFeedRoute: typeof AppTutorFeedRoute
  AppTutorHistoryRoute: typeof AppTutorHistoryRoute
  AppTutorLiveRoute: typeof AppTutorLiveRoute
  AppVoaeCentrosRoute: typeof AppVoaeCentrosRoute
  AppVoaeFeedRoute: typeof AppVoaeFeedRoute
  AppVoaeModeradoresRoute: typeof AppVoaeModeradoresRoute
  AppVoaeMuroRoute: typeof AppVoaeMuroRoute
  AppVoaeRecordsRoute: typeof AppVoaeRecordsRoute
  AppVoaeRecreacionRoute: typeof AppVoaeRecreacionRoute
  AppEmpleadoIndexRoute: typeof AppEmpleadoIndexRoute
  AppStudentIndexRoute: typeof AppStudentIndexRoute
  AppTutorIndexRoute: typeof AppTutorIndexRoute
  AppVoaeIndexRoute: typeof AppVoaeIndexRoute
  AppEmpleadoEventsIdRoute: typeof AppEmpleadoEventsIdRoute
  AppEmpleadoModeradorEventosRoute: typeof AppEmpleadoModeradorEventosRoute
  AppTutorEventsIdRoute: typeof AppTutorEventsIdRoute
  AppVoaeEventsIdRoute: typeof AppVoaeEventsIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppGestionRoute: AppGestionRouteWithChildren,
  AppEmpleadoCreateRoute: AppEmpleadoCreateRoute,
  AppEmpleadoEventosRoute: AppEmpleadoEventosRoute,
  AppEmpleadoFeedRoute: AppEmpleadoFeedRoute,
  AppEmpleadoHistoryRoute: AppEmpleadoHistoryRoute,
  AppEmpleadoLiveRoute: AppEmpleadoLiveRoute,
  AppEmpleadoMuroRoute: AppEmpleadoMuroRoute,
  AppEmpleadoPerfilRoute: AppEmpleadoPerfilRoute,
  AppStudentEventsRoute: AppStudentEventsRouteWithChildren,
  AppStudentFeedRoute: AppStudentFeedRoute,
  AppStudentHistoryRoute: AppStudentHistoryRoute,
  AppStudentMisEventosRoute: AppStudentMisEventosRoute,
  AppStudentMuroRoute: AppStudentMuroRoute,
  AppStudentPerfilRoute: AppStudentPerfilRoute,
  AppStudentSolicitarRoute: AppStudentSolicitarRoute,
  AppStudentSurveyRoute: AppStudentSurveyRoute,
  AppTutorCreateRoute: AppTutorCreateRoute,
  AppTutorEventosRoute: AppTutorEventosRoute,
  AppTutorFeedRoute: AppTutorFeedRoute,
  AppTutorHistoryRoute: AppTutorHistoryRoute,
  AppTutorLiveRoute: AppTutorLiveRoute,
  AppVoaeCentrosRoute: AppVoaeCentrosRoute,
  AppVoaeFeedRoute: AppVoaeFeedRoute,
  AppVoaeModeradoresRoute: AppVoaeModeradoresRoute,
  AppVoaeMuroRoute: AppVoaeMuroRoute,
  AppVoaeRecordsRoute: AppVoaeRecordsRoute,
  AppVoaeRecreacionRoute: AppVoaeRecreacionRoute,
  AppEmpleadoIndexRoute: AppEmpleadoIndexRoute,
  AppStudentIndexRoute: AppStudentIndexRoute,
  AppTutorIndexRoute: AppTutorIndexRoute,
  AppVoaeIndexRoute: AppVoaeIndexRoute,
  AppEmpleadoEventsIdRoute: AppEmpleadoEventsIdRoute,
  AppEmpleadoModeradorEventosRoute: AppEmpleadoModeradorEventosRoute,
  AppTutorEventsIdRoute: AppTutorEventsIdRoute,
  AppVoaeEventsIdRoute: AppVoaeEventsIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  VerificarRoute: VerificarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
